### ISSUE TITLE
Attributed products' sales are incorrectly aggregated

### ISSUE THREAD

**Issue by lat9** [lat9/sales_report#31]
... as reported in [this](https://www.zen-cart.com/showthread.php?44669-Sales-report-2-0&p=1387339#post1387339) Zen Cart support-thread posting.

It's unclear as to when that feature 'broke'.

**Comment by dennisns7d** [comment]
Having used this add-on, I was curious about this. I've narrowed it down to a change in admin/includes/classes/sales_report.php. This change happened during the **Re-factoring** commit on Oct 16, 2017.

3.1.1
`    function build_li_products($product) {
      $id = $this->timeframe_id;
      $pID = $product['uprid'];
`

3.2.0 and later
`    function build_li_products($product) 
    {
        $id = $this->timeframe_id;
        $pID = $product['id'];
`

Reversing this change appears to fix the problem.

I suspect that the call to zen_get_products_manufacturers_name should be using $product['id'] for its argument instead of $pID.

**Comment by dennisns7d** [comment]
I'm not seeing anything in this morning's commit #31 that addresses this issue.

**Comment by lat9** [comment]
Arggh.  Thanks, @dennisns7d.  I was in too much of a hurry.
